name: scanhub
description: "Rectify: Gelişmiş Mobil Belge Tarama Uygulaması."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Temel
  cupertino_icons: ^1.0.6
  
  # Kamera & Galeri
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  
  # OCR
  google_mlkit_text_recognition: ^0.11.0
  
  # Dosya & İzinler
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  
  # Tasarım
  google_fonts: ^6.1.0
  
  # PDF & Paylaşım
  pdf: ^3.10.4
  printing: ^5.11.1
  share_plus: ^7.2.2
  
  # Görüntü İşleme & Matematik
  image: ^4.5.4
  vector_math: ^2.1.4
  
  # İmza
  signature: ^5.4.1
  
  # Çizim & Düzenleme
  image_painter: ^0.7.0

  # Veritabanı & Güvenlik
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.6
  uuid: ^4.2.1
  
  # AI & Görüntü İşleme
  opencv_dart: ^1.0.0 
  tflite_flutter: ^0.12.1

  # Ads
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Model dosyasını tanıt
  assets:
    - assets/scan_model_pro.tflite

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21